client:
	mkdir -p build/bin/release
	gcc src/bin/client.c -o client
	mv client build/bin/release/client

server:
	mkdir -p build/bin/release
	gcc src/bin/server.c -o server
	mv server build/bin/release/server

clean:
	rm -rf build

